version: "2"

networks:
  cc-tools-demo-net:
    external: true

services:
  ccapi.org3.example.com:
    image: node:carbon
    ports:
      - 10PORT:PORT
    command: bash -c 'npm start; sleep infinity'
    volumes:
      - ./:/rest-server
      - ../fabric2/organizations/rest-certs/org3.example.com:/certs
    logging:
      options:
        max-size: 50m  
    env_file:
      - .env
    environment:
      - CONFIG_SDK_FILE=configsdk2-org3.yaml
      - DOCKER=1
      - CHANNEL=mainchannel
      - CCNAME=cc-tools-demo
    working_dir: /rest-server
    container_name: ccapi.org3.example.com
    networks:
      - cc-tools-demo-net
