openapi: 3.0.0
info:
  description: Documentação da API do Chaincode
  version: '0.1'
  title: CC Tools Demo
servers:
  - url: /api
tags:
  - name: Operações Básicas
paths:

  /invoke/{txName}:
    post:
      tags:
        - Operações Básicas
      summary: Executa a transação txName e escreve o resultado na blockchain.
      parameters:
        - in: path
          name: txName
          schema:
            type: string
          required: true
          description: Nome da transação a ser executada.
      requestBody:
        description: O corpo da requisição deve estar de acordo com a definição dos argumentos da transação.
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: OK
        '4XX':
          description: Bad Request
        5XX:
          description: Internal error

  /query/{txName}:
    post:
      tags:
        - Operações Básicas
      summary: Executa a transação txName e apenas retorna o resultado, sem escrevê-lo na blockchain.
      parameters:
        - in: path
          name: txName
          schema:
            type: string
          required: true
          description: Nome da transação a ser executada.
      requestBody:
        description: O corpo da requisição deve estar de acordo com a definição dos argumentos da transação.
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: OK
        '4XX':
          description: Bad Request
        5XX:
          description: Internal error

  /query/getHeader:
    get:
      tags:
        - Operações Básicas
      summary: Busca Informações do chaincode.
      responses:
        '200':
          description: OK
        5XX:
          description: Internal error.

  /query/getTx:
    get:
      tags:
        - Operações Básicas
      summary: Solicita a lista de transações definidas.
      responses:
        '200':
          description: OK
        5XX:
          description: Internal error
    post:
      tags:
        - Operações Básicas
      summary: Obtém a descrição de uma transação específica.
      requestBody:
        description: O campo txName deve conter o nome de uma transação definida pelo chaincode.
        content:
          application/json:
            schema:
              txName:
                type: string
            examples:
              getTx:
                value:
                  txName: getTx
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Transação não encontrada
        5XX:
          description: Internal error

  /query/getSchema:
    get:
      tags:
        - Operações Básicas
      summary: Pesquisa a lista de ativos existentes.
      responses:
        '200':
          description: OK
        5XX:
          description: Internal error
    post:
      tags:
        - Operações Básicas
      summary: Obtém a descrição de um tipo de asset específico.
      requestBody:
        description: O assetType deve conter um tipo de asset definido pelo chaincode.
        content:
          application/json:
            schema:
              assetType:
                type: string
            examples:
              person:
                value:
                  assetType: person
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Tipo de asset não encontrado
        5XX:
          description: Internal error

  /invoke/createAsset:
    post:
      tags:
        - Operações Básicas
      summary: Cria um ativo na blockchain
      requestBody:
        description: Os ativos que são propriedades de um novo ativo devem ter sido criados previamente.
        content:
          application/json:
            schema:
              type: object
              properties:
                asset:
                  type: array
                  items:
                    description: Qualquer tipo de ativo definido no chaincode. Consultar via getSchema.
                    type: object
            examples:
              person:
                summary: 'Create person'
                value:
                  asset:
                    - '@assetType': person
                      name: 'Maria'
                      id: '318.207.920-48'
      responses:
        '200':
          description: OK
        '400':
          description: Bad format
        '409':
          description: Asset already exists
        5XX:
          description: Internal error

  /query/readAsset:
    post:
      tags:
        - Operações Básicas
      summary: 'Obtém um ativo da blockchain a partir de sua chave primária.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: object
            examples:
              person:
                summary: person
                value:
                  key:
                    '@assetType': person
                    id: '318.207.920-48'
      responses:
        '200':
          description: OK
        '404':
          description: O ativo não foi encontrado.
        5XX:
          description: Internal error

  /query/readAssetHistory:
    post:
      tags:
        - Operações Básicas
      summary: 'Obtém o histórico de um ativo da blockchain a partir de sua chave primária.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: object
            examples:
              person:
                summary: person
                value:
                  key:
                    '@assetType': person
                    id: '318.207.920-48'
      responses:
        '200':
          description: OK
        '404':
          description: O ativo não foi encontrado.
        5XX:
          description: Internal error

  /query/search:
    post:
      tags:
        - Operações Básicas
      summary: Searches the blockchain world state using CouchDB rich queries
      description: 'Query JSON as defined by CouchDB docs: https://docs.couchdb.org/en/2.2.0/api/database/find.html'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  selector:
                    type: object
                  limit:
                    type: integer
                  bookmark:
                    type: string
            examples:
              personAll:
                summary: Get all assets of type person
                value:
                  query:
                    selector:
                      '@assetType': person
              personFirst10:
                summary: Get first 10 assets of type person
                value:
                  query:
                    selector:
                      '@assetType': person
                    limit: 10
                    bookmark: ''
              person10to20:
                summary: Get assets 10-20 of type person
                value:
                  query:
                    selector:
                      '@assetType': person
                    limit: 10
                    bookmark: 'g1AAAACGeJzLYWBgYMpgSmHgKy5JLCrJTq2MT8lPzkzJBYprF6QWFefnWaVaGBmbWCan6BqZJ6fpmqalWOgmGSWZ65qbWFommpkZWCYlW4KM4IAZQarmLAD0pSXP'
      responses:
        '200':
          description: OK
        '400':
          description: Bad format
        5XX:
          description: Internal error

  /invoke/updateAsset:
    put:
      tags:
        - Operações Básicas
      summary: Atualiza o estado de um ativo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '@assetType':
                  type: string
            examples:
              updateHeight:
                summary: 'Change person height'
                value:
                  update:
                    '@assetType': 'person'
                    name: 'Maria'
                    height: 1.66
        description: Precisa ter a chave primária do ativo e os campos a serem atualizados.
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad format
        '404':
          description: Asset not found
        5XX:
          description: Internal error

  /invoke/deleteAsset:
    delete:
      tags:
        - Operações Básicas
      summary: Deleta um ativo existente
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '@assetType':
                  type: string
            examples:
              deletePerson:
                summary: 'Delete person with name "Maria"'
                value:
                  key:
                    '@assetType': person
                    id: '318.207.920-48'
        description: Deve conter o campo que é chave do ativo definido pelo @assetType
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad format
        '404':
          description: Asset not found
        5XX:
          description: Internal error
